# Auctions DynamoDB Table
AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:       
    TableName: AuctionsTable-${self:provider.stage}     
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: endingAt
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: StatusAndEndDate
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: endingAt
            KeyType: RANGE
        Projection:
          # GSI creates virtual table from AuctionsTable, Projection ALL means carry all attributes
          ProjectionType: ALL

