version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless
      - echo Installing npm dependencies of dashboard service
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev
artifacts:
  files:
    - auction-artifact/*
  name: AuctionArtifact
cache:
  paths:
    - "node_modules/**/*"
